version: '3.9'

services:
  postgres:
    image: 'postgres:16.2'
    container_name: 'cookingmvc'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb